/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package de.example.api;

/**
 * TODO: unit test API
 * <p>
 * <li>Unit tests with bootique (https://bootique.io/docs/2.x/bootique-docs/)
 * <li>Use REST client to test (https://www.baeldung.com/jersey-jax-rs-client)
 *
 * @author Thomas Fritsche
 * @since 08.03.2022
 */
public class LibraryTest {

}
